<?php

namespace Ais\ProdiBundle\Repository;

/**
 * ProdiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdiRepository extends \Doctrine\ORM\EntityRepository
{
}
